sudo: false

git:
  depth: 1

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=master
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=master
    - python: "3.5"
      env: DJANGO=master

install:
  - pip install tox coveralls
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO
after_script:
  - coveralls
